openapi: 3.0.0
info:
  title: "{{title}}"
  version: "1.0"
paths:
  /transfer:
    post:
      operationId: inputOutputApi.create_job
      tags:
        - GET
      summary: GET file from uri
      description: Creates a new job or chain of jobs in the  worker USE ONLY ONE INPUT OR
        OUTPUT
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createJob"
        description: Service options
      responses:
        "201":
          description: Successfully created celery Job
servers:
  - url: /
components:
  schemas:
    createJob:
      type: object
      required:
        - input
        - output
      properties:
        input:
          type: object
          properties:
            type:
              type: object
              properties:
                 
                http:
                  type: object
                  properties:
                    passwd:
                      type: string
                    user:
                      type: string
                    uri:
                      type: string
                ftp:
                  type: object
                  properties:
                    passwd:
                      type: string
                    host:
                      type: string
                    user:
                      type: string
                    path:
                      type: string
        output:
          type: object
          properties:
            type:
              type: object
              properties:
                filesystem:
                  type: object
                  properties:
                    destPath:
                      type: string
                ftp:
                  type: object
                  properties:
                    ftpPasswd:
                      type: string
                    host:
                      type: string
                    ftpUser:
                      type: string
                    ftpPath:
                      type: string